services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: loanhub-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
    ports:
      - "1433:1433"
    volumes:
      - loanhub-sql-data:/var/opt/mssql
    networks:
      - loanhub-local

  backend:
    build:
      context: ./src/backend/LoanHub.Backend/
      dockerfile: Dockerfile
    container_name: loanhub-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:90
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LoanHubBackend;User Id=sa;Password=Password1!;TrustServerCertificate=True;
      - Authentication__Jwt__SecretKey=YourSuperSecretJwtKeyThatShouldBeAtLeast32CharactersLong123456
      - Authentication__Google__ClientId=791367453262-9f4jj6qq2388m974o4dr7n4gp6vmiegc.apps.googleusercontent.com
      - FrontendOrigin=http://localhost:8080
      - SendGrid__ApiKey=${SendGrid_SecretApiKey}
      - AzureBlob__ConnectionString=${AzureBlob_SecretConnectionString}
      - AzureBlob__Container=${AzureBlob_SecretContainerName}
      - TemplateName=Template dokumentu.docx
    ports:
      - "5000:90"
    networks:
      - loanhub-local
    depends_on:
      - sqlserver

  aggregator:
    build:
      context: ./src/aggregator/LoanHub.Aggregator/
      dockerfile: Dockerfile
    container_name: loanhub-aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:100
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LoanHubAggregator;User Id=sa;Password=Password1!;TrustServerCertificate=True;
      - DefaultBankUrl=http://backend:90/api/v1/
      - ArdalisBankUrl=http://backend:90/api/v1/
    ports:
      - "5001:100"
    networks:
      - loanhub-local
    depends_on:
      - backend
      - sqlserver

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
        GOOGLE_CLIENT_ID: 791367453262-9f4jj6qq2388m974o4dr7n4gp6vmiegc.apps.googleusercontent.com
    container_name: loanhub-frontend
    ports:
      - "8080:80"
    networks:
      - loanhub-local
    depends_on:
      - aggregator
      
networks:
  loanhub-local:
    driver: bridge

volumes:
  loanhub-sql-data:
