global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using AutoMapper;
global using LoanHub.Backend.Core;
global using LoanHub.Backend.Core.EntityAggregates.OfferAggregate;
global using LoanHub.Backend.Core.EntityAggregates.OfferAggregate.Dto;
global using LoanHub.Backend.Core.EntityAggregates.OfferAggregate.Specifications;
global using LoanHub.Backend.Core.EntityAggregates.ApplicationAggregate;
global using LoanHub.Backend.Core.EntityAggregates.ApplicationAggregate.DTO;
global using LoanHub.Backend.Core.EntityAggregates.ApplicationAggregate.Specifications;
global using LoanHub.Backend.Core.EntityAggregates.UserAggregate;
global using LoanHub.Backend.Core.Interfaces;
global using LoanHub.Backend.Core.Services;
global using LoanHub.Backend.UseCases.Features.Offer;
global using LoanHub.Backend.UseCases.Features.Offer.List;
global using LoanHub.Backend.UseCases.Mapping.Profiles;
global using MediatR;
global using NSubstitute;
global using Serilog.Extensions.Logging;
global using Shouldly;
global using Xunit;
global using OfferEntity = LoanHub.Backend.Core.EntityAggregates.OfferAggregate.Offer;
global using ApplicationEntity = LoanHub.Backend.Core.EntityAggregates.ApplicationAggregate.Application;