<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArdalisBank.Core\ArdalisBank.Core.csproj" />
  </ItemGroup>

</Project>
