<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />
  <ItemGroup>
    <Compile Remove="EntityAggregates\ApplicationAggregate\Specifications\**" />
    <EmbeddedResource Remove="EntityAggregates\ApplicationAggregate\Specifications\**" />
    <None Remove="EntityAggregates\ApplicationAggregate\Specifications\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="Ardalis.SharedKernel" />
    <PackageReference Include="Ardalis.SmartEnum" />
    <PackageReference Include="Ardalis.Specification" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
