global using System.Reflection;
global using Ardalis.GuardClauses;
global using Ardalis.SharedKernel;
global using Ardalis.Specification.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;